apiVersion: v1
kind: Deployment
metadata:
  name: iron-db
spec:
  replicas: 1
  selector:
    db: mariadb
  template:
    metadata:
      labels:
        db: mariadb
    spec:
      containers:
        - name: iron-db
          image: kodekloud/irondb:2.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Braavo
            - name: MYSQL_DATABASE
              value: lychee
            - name: MYSQL_USER
              value: lychee
            - name: MYSQL_PASSWORD
              value: lychee
