---
apiVersion: v1
kind: Service
metadata:
  name: iron-gallery-service
spec:
  selector:
    name: iron-gallery
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30099
    protocol: TCP
  type: NodePort
