---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  selector:
    app: drupal
  type: NodePort
  ports:
    - name: drupal
      port: 30095
      protocol: TCP
      targetPort: 80
