---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal--pv
spec:
  accessModes:
    - "ReadWriteOnce"
  capacity:
    storage: "5Gi"
  hostPath:
    path: /drupal-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
