# Name: drupal-mysql-service
# Type: ClusterIP
# Port: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  selector:
    app: drupal
  type: NodePort
  ports:
    - name: https
      port: 30095
      protocol: TCP
      targetPort: 80
