---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: developer
rules:
  - apiGroups: [""]
    resources: ["pods",
                "persistentvolumeclaims",
                "services"]
    verbs: ["*"]
