---
apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development
spec:
  selector:
    name: jekyll
    run: jekyll
  type: NodePort
  ports:
    - name: jekyll
      port: 8080
      targetPort: 4000
      nodePort: 30097
      protocol: TCP

